title: "CYBERSEC 520: Foundations of Artificial Intelligence in Cybersecurity"
author: "Michael Roman, Ph.D."
copyright: "2026"

logo: "logo.png"  # You can add a logo file later
execute:
  execute_notebooks: force

html:
  use_issues_button: true
  use_repository_button: true
  extra_navbar: |
    <p><b>Course:</b> ML in Cybersecurity</p>

repository:
  url: "https://github.com/mproman/CYBERSEC520/"
  path_to_book: ""
  branch: "main"

